# AWS CodeBuild buildspec to build the nginx alpine image
# By Jason Umiker (jason.umiker@gmail.com)

# This requires the following environment variables be set on the Project:
# AWS_DEFAULT_REGION 
# AWS_ACCOUNT_ID
# IMAGE_REPO_NAME
# IMAGE_TAG

version: 0.2
env:
  variables:
    IMAGE: "nginx
    IMAGE_TAG: "enginx"
phases:
  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=270809431272.dkr.ecr.us-east-2.amazonaws.com/nginx
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE .
      - docker tag $IMAGE:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build stage successfully completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"nginx","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json
